const UploadActionTypes = {
    SET_TRACK_NAME: 'SET_TRACK_NAME',
    SET_TRACK_DESCRIPTION: 'SET_TRACK_DESCRIPTION',
    SET_TAGGED_VERSION: 'SET_TAGGED_VERSION',
    SET_UNTAGGED_VERSION: 'SET_UNTAGGED_VERSION',
    SET_COVER_ART: 'SET_COVER_ART',
    SET_TRACK_STEMS: 'SET_TRACK_STEMS'
};

export default UploadActionTypes;